management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082
  tomcat:
    threads:
      #最大工作线程数
      max: 200
      #最小工作线程数
      min-spare: 200

spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.2.175:3306/javaee_lab2?serverTimezone=GMT%2B8
    username: root
    password: 6585
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      #初始化时建立物理连接的个数
      initial-size: 100
      #最小连接池数量
      min-idle: 100
      #最大连接池数量
      max-active: 200
      #获取连接时最大等待时间
      max-wait: 60000
      #配置监控页面访问登录名及密码
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*

      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 1000
      validation-query: select 1
    sql-script-encoding: UTF-8

mybatis:
  #domain对象的包
  type-aliases-package: org.javaee.testmybatis.model
  #mapper.xml所在的位置
  mapper-locations: org.javaee.testmybatis.model.mapper/*.xml
  #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
  configuration:
    #输出产生的SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

